# ---------------------------------------------------------------------------
# 2b_North_RiparianWSlope.py
# Created on: 2011-06-15 08:26:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
north_objects = "north_objects"
EP_RIP_dbf = "C:\\WorkSpace\\Phase4\\EP_RIP.dbf"
CH_RIP_dbf = "C:\\WorkSpace\\Phase4\\CH_RIP.dbf"
north_objects__7_ = "north_objects"
NonJuniper_Chihuahuan = "NonJuniper_Chihuahuan"
north_objects__13_ = "north_objects"
north_objects__19_ = "north_objects"
north_objects__24_ = "north_objects"
bleg = "bleg"
north_objects__2_ = "north_objects"
north_objects__30_ = "north_objects"
north_objects__4_ = "north_objects"
north_objects__5_ = "north_objects"
north_objects__3_ = "north_objects"
north_objects__6_ = "north_objects"
north_objects__9_ = "north_objects"
north_objects__10_ = "north_objects"
north_objects__11_ = "north_objects"
north_objects__39_ = "north_objects"
north_objects__14_ = "north_objects"
north_objects__15_ = "north_objects"
north_objects__17_ = "north_objects"
north_objects__20_ = "north_objects"
north_objects__21_ = "north_objects"
north_objects__22_ = "north_objects"
north_objects__25_ = "north_objects"
north_objects__26_ = "north_objects"
north_objects__27_ = "north_objects"
north_objects__28_ = "north_objects"

# Process: Add Join
arcpy.AddJoin_management(north_objects, "lulc", EP_RIP_dbf, "COVERTYPE", "KEEP_ALL")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(north_objects__2_, "NEW_SELECTION", "\"north_objects.Basin\" = 'Edwards Plateau' and ( \"north_objects.riparian24\" = 1  or \"north_objects.Vegname\" like '%Riparian%' or \"north_objects.Vegname\" = 'Ramadero')")

# Process: Calculate Field
arcpy.CalculateField_management(north_objects__30_, "north_objects.VegNum", "[EP_RIP.SYSTEM]", "VB", "")

# Process: Remove Join
arcpy.RemoveJoin_management(north_objects__4_, "EP_RIP")

# Process: Add Join (2)
arcpy.AddJoin_management(north_objects, "lulc", CH_RIP_dbf, "COVERTYPE", "KEEP_ALL")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(north_objects__5_, "NEW_SELECTION", "\"north_objects.Basin\" = 'Chihuahuan' and ( \"north_objects.riparian24\" = 1  or \"north_objects.Vegname\" like '%Riparian%' or \"north_objects.Vegname\" = 'Ramadero')")

# Process: Calculate Field (2)
arcpy.CalculateField_management(north_objects__3_, "north_objects.VegNum", "[CH_RIP.SYSTEM] ", "VB", "")

# Process: Remove Join (2)
arcpy.RemoveJoin_management(north_objects__6_, "CH_RIP")

# Process: Select Semi-arid Juniper
arcpy.SelectLayerByAttribute_management(north_objects__7_, "NEW_SELECTION", "\"VegNum\" = 1215 and \"lulc\" = 11")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(north_objects__9_, "INTERSECT", NonJuniper_Chihuahuan, "", "SUBSET_SELECTION")

# Process: Correct to TP: Mixed Shrub
arcpy.CalculateField_management(north_objects__10_, "VegNum", "8306", "VB", "")

# Process: Select Layer By Attribute (4)
arcpy.SelectLayerByAttribute_management(north_objects__11_, "CLEAR_SELECTION", "")

# Process: Select Layer By Attribute (5)
arcpy.SelectLayerByAttribute_management(north_objects__13_, "NEW_SELECTION", "\"lulc\" = 37 and \"riparian24\" = 1")

# Process: Calculate Field (4)
arcpy.CalculateField_management(north_objects__39_, "VegNum", "1405", "VB", "")

# Process: Select Layer By Attribute (6)
arcpy.SelectLayerByAttribute_management(north_objects__14_, "NEW_SELECTION", "\"lulc\" = 37 and \"riparian24\" = 0")

# Process: Calculate Field (5)
arcpy.CalculateField_management(north_objects__15_, "VegNum", "1215", "VB", "")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(north_objects__17_, "CLEAR_SELECTION", "")

# Process: Select Juniper Forest
arcpy.SelectLayerByAttribute_management(north_objects__19_, "NEW_SELECTION", "\"VegNum\" = 1101")

# Process: Select Layer By Location (2)
arcpy.SelectLayerByLocation_management(north_objects__20_, "INTERSECT", NonJuniper_Chihuahuan, "", "SUBSET_SELECTION")

# Process: Calculate Field (3)
arcpy.CalculateField_management(north_objects__21_, "VegNum", "8306", "VB", "")

# Process: Select Layer By Attribute (7)
arcpy.SelectLayerByAttribute_management(north_objects__22_, "CLEAR_SELECTION", "")

# Process: Select Live Oak Forest
arcpy.SelectLayerByAttribute_management(north_objects__24_, "NEW_SELECTION", "\"VegNum\" = 1102 ")

# Process: Select Layer By Location (3)
arcpy.SelectLayerByLocation_management(north_objects__25_, "INTERSECT", NonJuniper_Chihuahuan, "", "SUBSET_SELECTION")

# Process: Select Layer By Location (4)
arcpy.SelectLayerByLocation_management(north_objects__26_, "INTERSECT", bleg, "", "REMOVE_FROM_SELECTION")

# Process: Calculate Field (6)
arcpy.CalculateField_management(north_objects__27_, "VegNum", "8306", "VB", "")

# Process: Select Layer By Attribute (9)
arcpy.SelectLayerByAttribute_management(north_objects__28_, "CLEAR_SELECTION", "")

