# ---------------------------------------------------------------------------
# 3_North_slope_stockton_shrub.py
# Created on: 2011-06-15 08:26:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
north_objects = "north_objects"
north_objects__4_ = "north_objects"
SLPXWALK_dbf = "C:\\WorkSpace\\Phase4\\SLPXWALK.DBF"
north_objects__8_ = "north_objects"
NonJuniper_Chihuahuan = "NonJuniper_Chihuahuan"
bleg = "bleg"
north_objects__19_ = "north_objects"
bleg__2_ = "bleg"
north_objects__3_ = "north_objects"
north_objects__2_ = "north_objects"
north_objects__6_ = "north_objects"
north_objects__9_ = "north_objects"
north_objects__10_ = "north_objects"
north_objects__7_ = "north_objects"
north_objects__13_ = "north_objects"
north_objects__21_ = "north_objects"
north_objects__11_ = "north_objects"
north_objects__14_ = "north_objects"
north_objects__23_ = "north_objects"
north_objects__25_ = "north_objects"
north_objects__22_ = "north_objects"
north_objects__12_ = "north_objects"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(north_objects, "NEW_SELECTION", "\"epa_ecoreg\" =  '24e' and \"lulc\" = 7 and \"slope20\" = 0 and \"cliff\" = 0 and \"riparian24\" = 0 and (\"Ecogroup\" like 'Gravelly, %' or \"Ecogroup\" like 'Limestone%')")

# Process: Calculate Field
arcpy.CalculateField_management(north_objects__3_, "VegNum", "1207", "VB", "")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(north_objects__2_, "CLEAR_SELECTION", "")

# Process: Add Join
arcpy.AddJoin_management(north_objects__4_, "VegNum", SLPXWALK_dbf, "STANDARD", "KEEP_ALL")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(north_objects__6_, "NEW_SELECTION", "\"SLPXWALK.SLOPE\" is not null AND \"north_objects.slope20\" =1 AND \"north_objects.cliff\" = 0")

# Process: Calculate Field (2)
arcpy.CalculateField_management(north_objects__9_, "north_objects.VegNum", "[SLPXWALK.SLOPE]", "VB", "")

# Process: Select Layer By Attribute (4)
arcpy.SelectLayerByAttribute_management(north_objects__10_, "CLEAR_SELECTION", "")

# Process: Remove Join
arcpy.RemoveJoin_management(north_objects__7_, "SLPXWALK")

# Process: Select Layer By Attribute (5)
arcpy.SelectLayerByAttribute_management(north_objects__8_, "NEW_SELECTION", "\"VegNum\" = 1001 or \"VegNum\" = 1003 or \"VegNum\" = 1002")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(north_objects__13_, "INTERSECT", NonJuniper_Chihuahuan, "", "SUBSET_SELECTION")

# Process: Select Layer By Location (2)
arcpy.SelectLayerByLocation_management(north_objects__21_, "INTERSECT", bleg, "", "REMOVE_FROM_SELECTION")

# Process: Calculate Field (3)
arcpy.CalculateField_management(north_objects__11_, "VegNum", "8704", "VB", "")

# Process: Select Layer By Attribute (6)
arcpy.SelectLayerByAttribute_management(north_objects__14_, "CLEAR_SELECTION", "")

# Process: Select Layer By Attribute (7)
arcpy.SelectLayerByAttribute_management(north_objects__19_, "NEW_SELECTION", "\"VegNum\" = 1005")

# Process: Select Layer By Location (3)
arcpy.SelectLayerByLocation_management(north_objects__23_, "INTERSECT", NonJuniper_Chihuahuan, "", "SUBSET_SELECTION")

# Process: Select Layer By Location (4)
arcpy.SelectLayerByLocation_management(north_objects__25_, "INTERSECT", bleg__2_, "", "REMOVE_FROM_SELECTION")

# Process: Calculate Field (5)
arcpy.CalculateField_management(north_objects__22_, "VegNum", "8706", "VB", "")

# Process: Select Layer By Attribute (8)
arcpy.SelectLayerByAttribute_management(north_objects__12_, "CLEAR_SELECTION", "")

