# ---------------------------------------------------------------------------
# export.py
# Created on: 2012-07-25 09:35:54.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
tm_objects_3 = "G:\\2011_MDC_ELK\\test_rasters\\tm_objects_3.shp"
outpath = "G:\\2011_MDC_Elk\\test_rasters\\"

# Process: Polygon to Raster
#arcpy.PolygonToRaster_conversion(tm_objects_3, "Max_pixel_", max_1, "CELL_CENTER", "NONE", "30")

fieldList = arcpy.ListFields("g:\\2011_mdc_elk\\test_rasters\\tm_objects_3.shp")

for field in fieldList:
    print "working on " + field.name + "\a"
    outrast = "%s%s" % (outpath, field.name) 
#    print outrast
    if ((field.name != "FID") & (field.name != "Shape")):
#    if (field.name == "Max_pixel2"):
        tempEnvironment0 = arcpy.env.snapRaster        
        arcpy.env.snapRaster = "G:\\2011_MDC_Elk\\final\\Elk_Final to deliver\\DATA\\Elk_Habitat_LULC_30m.img"         
        arcpy.PolygonToRaster_conversion(tm_objects_3, field.name, outrast, "CELL_CENTER", "NONE", "30")		
        arcpy.env.snapRaster = tempEnvironment0         
          #print("{0} is a type of {1} with a length of {2}"
              #.format(field.name, field.type, field.length))
print "complete \a\a\a\a\a\a\a\a\a\a\a"