# ---------------------------------------------------------------------------
# gridify.py
# Created on: 2011-07-16 09:00:40.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from time import time
from string import zfill
from datetime import date

outf = open ("c:/workspace/phase4/modellog.txt", "a")
outf.writelines("\n" + str(date.today()) + " ---Gridify---\n")
def elapsed_time(t0):
	seconds = int(round(time() - t0))
	h,rsecs = divmod(seconds,3600)
	m,s = divmod(rsecs,60)
	return zfill(h,2) + ":" + zfill(m,2) + ":" + zfill(s,2)
starttime = time()
processstart = time()


# Local variables:
south_objects = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_objects"
p123 = "C:\\WorkSpace\\Grids\\p123"
central_objects = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_objects"
north_objects = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_objects"
p4south = "C:\\WorkSpace\\Phase4\\p4south"
p4central = "C:\\WorkSpace\\Phase4\\p4central"
p4north = "C:\\WorkSpace\\Phase4\\p4north"
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\WorkSpace\\Grids\\p123"

# Process: Polygon to Raster
try:
	arcpy.PolygonToRaster_conversion(south_objects, "VegNum", p4south, "CELL_CENTER", "NONE", p123)
	arcpy.env.snapRaster = tempEnvironment0
	outf.writelines("Completed south. " + elapsed_time(processstart) + "\n")
	processstart = time()
except:
	outf.writelines("Aborted south. " + elapsed_time(processstart) + "\n")
	processstart = time()
	

# Process: Polygon to Raster (2)
try:
	arcpy.PolygonToRaster_conversion(central_objects, "VegNum", p4central, "CELL_CENTER", "NONE", p123)
	arcpy.env.snapRaster = tempEnvironment0
	outf.writelines("Completed central. " + elapsed_time(processstart) + "\n")
	processstart = time()
except:
	outf.writelines("Aborted central. " + elapsed_time(processstart) + "\n")
	processstart = time()

# Process: Polygon to Raster (3)
try:
	arcpy.PolygonToRaster_conversion(north_objects, "VegNum", p4north, "CELL_CENTER", "NONE", p123)
	arcpy.env.snapRaster = tempEnvironment0
	outf.writelines("Completed north. " + elapsed_time(processstart) + "\n")
	processstart = time()
except:
	outf.writelines("Aborted north. " + elapsed_time(processstart) + "\n")
	processstart = time()

outf.writelines("Finised grids " + elapsed_time(starttime) + "\n")
print "Finished - Elapsed Time = " + elapsed_time(starttime)
outf.close()
