# ---------------------------------------------------------------------------
# mrgdslv.py
# Created on: 2011-06-17 14:32:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import management as DM
arcpy.env.workspace = "C:/WorkSpace/Phase4"

# Local variables:
north = "p4_objects_working.gdb\\north_dslv"
south = "p4_objects_working.gdb\\south_dslv"
central = "p4_objects_working.gdb\\central_dslv"
merged = "p4_objects_working.gdb\\p4_dslv_Merge"
mrgd_dslvd = "p4_objects_working.gdb\\p4veg"

# Process: Merge
DM.Merge("p4_objects_working.gdb\\north_dslv;p4_objects_working.gdb\\south_dslv; p4_objects_working.gdb\\central_dslv", merged, "VegNum \"VegNum\" true true false 4 Long 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,VegNum,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,VegNum,-1,-1;VegName \"VegName\" true true false 100 Text 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,VegName,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,VegName,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,Shape_Length,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,Shape_Area,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,Shape_Area,-1,-1")

# Process: Dissolve
DM.Dissolve(merged, mrgd_dslvd, "VegNum;VegName", "", "MULTI_PART", "DISSOLVE_LINES")

