# ---------------------------------------------------------------------------
# mrgdslv2.py
# Created on: 2011-06-17 16:06:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
central_dslv = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_dslv"
north_dslv = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv"
south_dslv = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv"
Output_Dataset = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_dslv_Merge"
p4veg = "C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\p4veg"

# Process: Merge
arcpy.Merge_management("C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_dslv;C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv;C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv", Output_Dataset, "VegNum \"VegNum\" true true false 4 Long 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_dslv,VegNum,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,VegNum,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,VegNum,-1,-1;VegName \"VegName\" true true false 100 Text 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_dslv,VegName,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,VegName,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,VegName,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_dslv,Shape_Length,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,Shape_Length,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\central_dslv,Shape_Area,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\north_dslv,Shape_Area,-1,-1,C:\\WorkSpace\\Phase4\\p4_objects_working.gdb\\south_dslv,Shape_Area,-1,-1")

# Process: Dissolve
arcpy.Dissolve_management(Output_Dataset, p4veg, "VegNum;VegName", "", "MULTI_PART", "DISSOLVE_LINES")

