# ---------------------------------------------------------------------------
# p4dslv.py
# Created on: 2011-06-16 11:29:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.workspace = "C:/WorkSpace/Phase4"

objects = "test.gdb/north_objects"
dslv = "test.gdb/north_dslv"

arcpy.Dissolve_management(objects, dslv, "VegNum;VegName", "", "MULTI_PART", "DISSOLVE_LINES")

