# ---------------------------------------------------------------------------
# p4models.py
# Created on: 2011-06-09 11:32:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
QKEY01_dbf__2_ = "C:\\WorkSpace\\Phase4\\QKEY01.DBF"
north_objects = "north_objects"
QKEY03_dbf = "C:\\WorkSpace\\Phase4\\QKEY03.dbf"
QKEY05_dbf = "C:\\WorkSpace\\Phase4\\QKEY05.dbf"
QKEY07_dbf = "C:\\WorkSpace\\Phase4\\QKEY07.dbf"
QKEY09_dbf = "C:\\WorkSpace\\Phase4\\QKEY09.dbf"
QKEY11_dbf = "C:\\WorkSpace\\Phase4\\QKEY11.dbf"
QKEY13_dbf = "C:\\WorkSpace\\Phase4\\QKEY13.dbf"
QKEY15_dbf = "C:\\WorkSpace\\Phase4\\QKEY15.dbf"
QKEY19_dbf = "C:\\WorkSpace\\Phase4\\QKEY19.dbf"
QKEY21_dbf = "C:\\WorkSpace\\Phase4\\QKEY21.dbf"
QKEY23_dbf = "C:\\WorkSpace\\Phase4\\QKEY23.dbf"
QKEY25_dbf = "C:\\WorkSpace\\Phase4\\QKEY25.dbf"
QKEY27_dbf = "C:\\WorkSpace\\Phase4\\QKEY27.dbf"
QKEY31_dbf = "C:\\WorkSpace\\Phase4\\QKEY31.dbf"
north_objects__4_ = "north_objects"
north_objects__5_ = "north_objects"
north_objects__6_ = "north_objects"
north_objects__2_ = "north_objects"
north_objects__44_ = "north_objects"
north_objects__10_ = "north_objects"
north_objects__8_ = "north_objects"
north_objects__7_ = "north_objects"
north_objects__9_ = "north_objects"
north_objects__11_ = "north_objects"
north_objects__46_ = "north_objects"
north_objects__12_ = "north_objects"
north_objects__14_ = "north_objects"
north_objects__13_ = "north_objects"
north_objects__15_ = "north_objects"
north_objects__17_ = "north_objects"
north_objects__16_ = "north_objects"
north_objects__18_ = "north_objects"
north_objects__20_ = "north_objects"
north_objects__22_ = "north_objects"
north_objects__19_ = "north_objects"
north_objects__23_ = "north_objects"
north_objects__21_ = "north_objects"
north_objects__42_ = "north_objects"
north_objects__26_ = "north_objects"
north_objects__24_ = "north_objects"
north_objects__25_ = "north_objects"
north_objects__29_ = "north_objects"
north_objects__27_ = "north_objects"
north_objects__28_ = "north_objects"
north_objects__32_ = "north_objects"
north_objects__30_ = "north_objects"
north_objects__31_ = "north_objects"
north_objects__35_ = "north_objects"
north_objects__33_ = "north_objects"
north_objects__34_ = "north_objects"
north_objects__38_ = "north_objects"
north_objects__36_ = "north_objects"
north_objects__37_ = "north_objects"
north_objects__41_ = "north_objects"
north_objects__39_ = "north_objects"
north_objects__40_ = "north_objects"

# Process: Add Join (2)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY01_dbf__2_, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(north_objects__4_, "NEW_SELECTION", "\"north_objects.lulc\" = 1")

# Process: Calculate Field
arcpy.CalculateField_management(north_objects__5_, "north_objects.VegNum", "[QKEY01.SYSTEM]", "VB", "")

# Process: Remove Join
arcpy.RemoveJoin_management(north_objects__6_, "QKEY01")

# Process: Add Join (3)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY03_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(north_objects__2_, "NEW_SELECTION", "\"north_objects.lulc\" = 3")

# Process: Calculate Field (2)
arcpy.CalculateField_management(north_objects__44_, "north_objects.VegNum", "[QKEY03.SYSTEM]", "VB", "")

# Process: Remove Join (2)
arcpy.RemoveJoin_management(north_objects__10_, "QKEY03")

# Process: Add Join (4)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY05_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(north_objects__8_, "NEW_SELECTION", "\"north_objects.lulc\" = 5")

# Process: Calculate Field (3)
arcpy.CalculateField_management(north_objects__7_, "north_objects.VegNum", "[QKEY05.SYSTEM]", "VB", "")

# Process: Remove Join (3)
arcpy.RemoveJoin_management(north_objects__9_, "QKEY05")

# Process: Add Join (5)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY07_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (4)
arcpy.SelectLayerByAttribute_management(north_objects__11_, "NEW_SELECTION", "\"north_objects.lulc\" =7")

# Process: Calculate Field (4)
arcpy.CalculateField_management(north_objects__46_, "north_objects.VegNum", "[QKEY07.SYSTEM]", "VB", "")

# Process: Remove Join (4)
arcpy.RemoveJoin_management(north_objects__12_, "QKEY07")

# Process: Add Join (6)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY09_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (5)
arcpy.SelectLayerByAttribute_management(north_objects__14_, "NEW_SELECTION", "\"north_objects.lulc\" = 9")

# Process: Calculate Field (5)
arcpy.CalculateField_management(north_objects__13_, "north_objects.VegNum", "[QKEY09.SYSTEM]", "VB", "")

# Process: Remove Join (5)
arcpy.RemoveJoin_management(north_objects__15_, "QKEY09")

# Process: Add Join (7)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY11_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (6)
arcpy.SelectLayerByAttribute_management(north_objects__17_, "NEW_SELECTION", "\"north_objects.lulc\" = 11")

# Process: Calculate Field (6)
arcpy.CalculateField_management(north_objects__16_, "north_objects.VegNum", "[QKEY11.SYSTEM]", "VB", "")

# Process: Remove Join (6)
arcpy.RemoveJoin_management(north_objects__18_, "QKEY11")

# Process: Add Join (8)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY13_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (7)
arcpy.SelectLayerByAttribute_management(north_objects__20_, "NEW_SELECTION", "\"north_objects.lulc\" = 13")

# Process: Calculate Field (7)
arcpy.CalculateField_management(north_objects__22_, "north_objects.VegNum", "[QKEY13.SYSTEM]", "VB", "")

# Process: Remove Join (7)
arcpy.RemoveJoin_management(north_objects__19_, "QKEY13")

# Process: Add Join (9)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY15_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (8)
arcpy.SelectLayerByAttribute_management(north_objects__23_, "NEW_SELECTION", "\"north_objects.lulc\" = 15")

# Process: Calculate Field (8)
arcpy.CalculateField_management(north_objects__21_, "north_objects.VegNum", "[QKEY15.SYSTEM]", "VB", "")

# Process: Remove Join (8)
arcpy.RemoveJoin_management(north_objects__42_, "QKEY15")

# Process: Add Join (10)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY19_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (9)
arcpy.SelectLayerByAttribute_management(north_objects__26_, "NEW_SELECTION", "\"north_objects.lulc\" = 19")

# Process: Calculate Field (9)
arcpy.CalculateField_management(north_objects__24_, "north_objects.VegNum", "[QKEY19.SYSTEM]", "VB", "")

# Process: Remove Join (9)
arcpy.RemoveJoin_management(north_objects__25_, "QKEY19")

# Process: Add Join (11)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY21_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (10)
arcpy.SelectLayerByAttribute_management(north_objects__29_, "NEW_SELECTION", "\"north_objects.lulc\" = 21")

# Process: Calculate Field (10)
arcpy.CalculateField_management(north_objects__27_, "north_objects.VegNum", "[QKEY21.SYSTEM]", "VB", "")

# Process: Remove Join (10)
arcpy.RemoveJoin_management(north_objects__28_, "QKEY21")

# Process: Add Join (12)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY23_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (11)
arcpy.SelectLayerByAttribute_management(north_objects__32_, "NEW_SELECTION", "\"north_objects.lulc\" = 23")

# Process: Calculate Field (11)
arcpy.CalculateField_management(north_objects__30_, "north_objects.VegNum", "[QKEY23.SYSTEM]", "VB", "")

# Process: Remove Join (11)
arcpy.RemoveJoin_management(north_objects__31_, "QKEY23")

# Process: Add Join (13)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY25_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (12)
arcpy.SelectLayerByAttribute_management(north_objects__35_, "NEW_SELECTION", "\"north_objects.lulc\" = 25")

# Process: Calculate Field (12)
arcpy.CalculateField_management(north_objects__33_, "north_objects.VegNum", "[QKEY25.SYSTEM]", "VB", "")

# Process: Remove Join (12)
arcpy.RemoveJoin_management(north_objects__34_, "QKEY25")

# Process: Add Join (14)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY27_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (13)
arcpy.SelectLayerByAttribute_management(north_objects__38_, "NEW_SELECTION", "\"north_objects.lulc\" = 27")

# Process: Calculate Field (13)
arcpy.CalculateField_management(north_objects__36_, "north_objects.VegNum", "[QKEY27.SYSTEM]", "VB", "")

# Process: Remove Join (13)
arcpy.RemoveJoin_management(north_objects__37_, "QKEY27")

# Process: Add Join (15)
arcpy.AddJoin_management(north_objects, "Ecogroup", QKEY31_dbf, "ECOGROUP", "KEEP_ALL")

# Process: Select Layer By Attribute (14)
arcpy.SelectLayerByAttribute_management(north_objects__41_, "NEW_SELECTION", "\"north_objects.lulc\" = 31")

# Process: Calculate Field (14)
arcpy.CalculateField_management(north_objects__39_, "north_objects.VegNum", "[QKEY31.SYSTEM]", "VB", "")

# Process: Remove Join (14)
arcpy.RemoveJoin_management(north_objects__40_, "QKEY31")

