# ---------------------------------------------------------------------------
# point2raster.py
# Created on: 2013-03-20 10:47:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os 
currentdir = os.getcwd()

# Local variables:
qoa = "D:\\Projects\\Enduring Features\\Land Facets\\test.gdb\\qoa"
qoa_raster = "%s\\qoa%s" % (currentdir, "_rast")
#qoa_raster = "D:\\Projects\\Enduring Features\\Land Facets\\qoa_raster"

# Process: Point to Raster
arcpy.PointToRaster_conversion(qoa, "cluster", qoa_raster, "MOST_FREQUENT", "NONE", "30")

