# ---------------------------------------------------------------------------
# saltcedar.py
# Created on: 2011-11-29 09:16:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
north_objects = "north_objects"
p4soils_working = "p4soils_working"
north_objects__2_ = "north_objects"
north_objects__3_ = "north_objects"

# Process: Add Join
arcpy.AddJoin_management(north_objects, "morap_id", p4soils_working, "morap_id", "KEEP_ALL")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(north_objects__2_, "NEW_SELECTION", "\"p4soils_working.ecoclassna\" like 'SALTY BOTT%' and ( \"north_objects.lulc\" = 3 or \"north_objects.lulc\" = 5 or \"north_objects.lulc\" = 11 or \"north_objects.lulc\" = 19 or \"north_objects.lulc\" = 31) and \"north_objects.Basin\" = 'Chihuahuan'")

# Process: Calculate Field
arcpy.CalculateField_management(north_objects__3_, "north_objects.VegNum", "9204", "VB", "")

